### ISSUE TITLE
GKE-specific?

### ISSUE THREAD

**Issue by MPV** [GoogleCloudPlatform/gke-fqdnnetworkpolicies-golang#18]
Given the `GKE` prefix in the name, is that to say there are any limitations on why this wouldn't be suitable to run elsewhere than only in GKE?

**Comment by MPV** [comment]
Given that it "just performs lookups and created regular NetworkPolicies" (🎉), it doesn't sound GKE-specific to me?

(but I have mostly checked the README at the moment, might dig more into the source code soon too)

**Comment by MPV** [comment]
For reference, this one seems like a very similar alternative, no?

https://github.com/giantswarm/dns-network-policy-operator

**Comment by MrTrustor** [comment]
We have developed this on GKE, and only ever tested it on GKE. In particular, we may be indirectly relying on the behaviour of GKE for DNS resolution in non-obvious ways.
So I think there's a chance it will work on non-GKE cluster, but there's also a chance that it's going to fail in strange ways due to differences on how DNS resolution actually works.

For the other project, I had never seen it, but yes, it does look similar.
