### ISSUE TITLE
How would this work if the target hostname's IP addresses changes?

### ISSUE THREAD

**Issue by AgrimPrasad** [GoogleCloudPlatform/gke-fqdnnetworkpolicies-golang#51]
Hi,

Firstly, thanks for this much-needed FQDN based Network policy generator!

We are considering using FQDN network policies for security enhancement of egress traffic from our GKE cluster. However, we have a concern as below:

- Say we whitelist an FQDN: `x.example.com` with IP addresses A, B, C.
- 1 year later, the FQDN's IP addresses change to X, Y, Z.

Would we now see downtime where our egress is blocked until the FQDN is polled again for the latest IP addresses (which could take several hours I believe?)

**Comment by MrTrustor** [comment]
Hi,

The GKE team actually just released an official feature that does the same thing as this project: https://cloud.google.com/kubernetes-engine/docs/how-to/fqdn-network-policies
We encourage you to adopt that instead of this project, as we will not be adding new functionality here.

To answer your question (in the context of this project only, not of the official GKE feature): yes, there is a risk that is inherent to how DNS works in the first place. The actual blocking of traffic happens at the IP level, so we need to resolve FQDNs to IP addresses, and we are subject to DNS propagation times.

This project polls the FQDN every time the TTL of the record expires (i.e if your DNS record TTL is 300s, this projects polls every 300s, since there wouldn't be any change before that anyway).

Hope this helps
